# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class UploadImageBody(BaseModel):
    image: bytes
    caption: Optional[str] = None


class UploadImageResponse(RootModel[None]):
    """Uploaded"""

    root: None
