# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class BinaryImage(RootModel[bytes]):
    root: bytes


class ImageUpload(BaseModel):
    image: bytes
    caption: Optional[str] = None


class UploadImageBody(BaseModel):
    image: bytes
    caption: Optional[str] = None


class UploadImageResponse(RootModel[None]):
    """Uploaded"""

    root: None


class UploadImageRefBody(RootModel[ImageUpload]):
    root: ImageUpload


class UploadImageRefResponse(RootModel[None]):
    """Uploaded"""

    root: None


class UploadImagesBody(BaseModel):
    images: list[BinaryImage]
    caption: Optional[str] = None


class UploadImagesResponse(RootModel[None]):
    """Uploaded"""

    root: None


class SendBinaryBodyBody(RootModel[bytes]):
    root: bytes


class SendBinaryBodyResponse(RootModel[None]):
    """Sent"""

    root: None
