# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client


class Sdk(Client):
    def upload_image(self, image: bytes, caption: Optional[str] = None):
        params = build_client_params([{"in": "multipart", "key": "image", "binary": True}, {"in": "multipart", "key": "caption"}], image=image, caption=caption)
        return self.request_options("post", "/images", params)
